const fs = require('fs');
const path = require('path');
const { execGit } = require('./git-scanner');

function generateHandoffContent(workspaceRoot, data) {
  const timestamp = new Date().toISOString().replace(/[:.]/g, '-').slice(0, 19);
  const gitDiff = data.gitDiff || '';
  const tickets = data.tickets || { issues: [], pullRequests: [] };
  const context = data.context || {};
  const wayfinder = data.wayfinder || {};

  return `# Handoff — ${timestamp}

## Session Summary
- **Workspace**: \`${workspaceRoot}\`
- **Branch**: \`${data.branch || 'unknown'}\`
- **Last Commit**: ${data.lastCommit || 'N/A'}
- **Uncommitted Changes**: ${gitDiff ? 'Yes' : 'No'}

## Git Status
\`\`\`
${gitDiff || 'Clean'}
\`\`\`

## Open Issues & PRs
${tickets.issues.length ? tickets.issues.map(i => `- **#${i.number}** ${i.title} (${i.state})`).join('\n') : 'No open issues'}
${tickets.pullRequests.length ? tickets.pullRequests.map(p => `- **#${p.number}** ${p.title} (${p.state})`).join('\n') : 'No open PRs'}

## Context (CONTEXT.md)
${context.domainTerms ? context.domainTerms.map(t => `- ${t}`).join('\n') : 'No domain terms found'}
${context.adrs ? context.adrs.map(a => `- ${a}`).join('\n') : 'No ADRs found'}

## WAYFINDER.md Decision Nodes
${wayfinder.decisions ? wayfinder.decisions.map(d => `- ${d}`).join('\n') : 'No decision nodes found'}
${wayfinder.fogItems ? `- **Fog Items**: ${wayfinder.fogItems} unscoped tasks` : ''}

## Next Actions
1. Review uncommitted changes
2. Address failing tests if any
3. Update WAYFINDER.md fog items
4. Commit or hand off

## Suggested Skills
- /tdd
- /grill-with-docs
- /handoff
- /code-review

---
*Generated by OverApp Command Center*
`;
}

async function createHandoff(workspaceRoot) {
  const handoffsDir = path.join(workspaceRoot, '.agents', 'handoffs');
  try {
    if (!fs.existsSync(handoffsDir)) fs.mkdirSync(handoffsDir, { recursive: true });
  } catch {}

  const timestamp = new Date().toISOString().replace(/[:.]/g, '-').slice(0, 19);
  const filename = `handoff-${timestamp}.md`;
  const filepath = path.join(handoffsDir, filename);

  let gitDiff = '';
  try { gitDiff = await execGit(['diff', '--stat'], workspaceRoot); } catch {}
  let branch = '';
  try { branch = await execGit(['branch', '--show-current'], workspaceRoot); } catch {}
  let lastCommit = '';
  try { lastCommit = await execGit(['log', '-1', '--oneline'], workspaceRoot); } catch {}

  const { parseWayfinder, parseContext } = require('./skill-parser');
  const context = parseContext(path.join(workspaceRoot, 'CONTEXT.md'));
  const wayfinder = parseWayfinder(path.join(workspaceRoot, 'WAYFINDER.md'));

  const { getTickets } = require('./gh-bridge');
  const tickets = await getTickets(workspaceRoot);

  const content = generateHandoffContent(workspaceRoot, {
    gitDiff, branch, lastCommit, tickets, context, wayfinder,
  });

  fs.writeFileSync(filepath, content);
  return { filepath, filename, content };
}

module.exports = { createHandoff, generateHandoffContent };
